apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes: 
  - ReadWriteMany
  # just for now
  hostPath:
    path: /mnt/test-data
