apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: lab-k8s-services
  name: lab-k8s-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testclusterip
  name: testclusterip
  namespace: lab-k8s-services
spec:
  progressDeadlineSeconds: 600
  replicas: 3 
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: testclusterip
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testclusterip
    spec:
      containers:
      - image: rwxrob/gotcptest
        imagePullPolicy: Always
        name: gotcptest
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
