apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: Namespace
  metadata:
    name: filler

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: filler-pv
    labels:
      type: local
  spec:
    accessModes:
      - ReadWriteOnce
    capacity: 
      storage: 3Gi
    hostPath:
      path: "/mnt/data"

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: filler-pvc
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi

- apiVersion: v1
  kind: Pod
  metadata:
    name: filler
  spec:
    volumes:
      - name: filler-pv-storage
        persistentVolumeClaim:
          claimName: filler-pvc
    containers:
    - image: alpine
      command:
        - tail
        - -f 
        - /dev/null
      name: filldisk
      volumeMounts:
        - mountPath: /blah
          name: filler-pv-storage
